import { Providers } from './Provider'
import './globals.scss'

export const metadata = {
  title: 'User Management',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers >
          {children}
        </Providers></body>
    </html>
  )
}
